#!/bin/bash

function sub() {
    sed -i "s#\([a-zA-Z_.]*\)\.$1\([ \.;),-\+\*}]\)#TFLD(\1).$1\2#g" *.qc ../share/*.qc
    grep $1 tfortmap.qc tforttm.qc
}

sub vote_trick
sub is_undercover
sub is_building
sub is_detpacking
sub is_button_feigning
sub feign_next_damage
sub is_unabletospy
sub is_zooming
sub default_sensitivity
sub default_fov
sub current_fov
sub zoom_fov
sub zoom_last
sub vote_next
sub vote_race
sub force_next
sub vote_close
sub aura_active
sub aura_healamount
sub aura_healcount
sub aura_healtime
sub has_throwngren
sub has_changedteam
sub has_changedclass
sub has_disconnected
sub has_menutimer
sub has_voted_map
sub menu_time
sub display_tip
sub tip_type
sub tip_time
sub is_disarming
sub cheat_check
sub detpack_left
sub pipecooldown
sub detpipe_nesting
sub disguise_skin
sub queue_skin
sub last_selected_skin
sub disguise_team
sub queue_team
sub last_team
sub feign_areachecked
sub regen_time
sub regen_cooldown
sub saveme_time
sub undercover_timer
sub power_time
sub sentry_ticks
sub dispenser_ticks
sub building_percentage
sub ident_string
sub ident_time
sub autoid_type
sub autoid_time
sub motd
sub current_menu_type
sub current_menu_page
sub menu_count
sub menu_displaytime
sub has_flag
sub infection_team_no
sub fragstreak
sub nopickup
sub building_wait
sub has_dispenser
sub has_sentry
sub sentry_ent
sub real_frags
sub respawn_time
sub suicide_time
sub deff;
sub dimmune;
sub duse;
sub next_saveme_sound
sub immune_to_check
sub no_active_nail_grens;
sub noammo
sub numflames
sub icdmgtime
sub undercover_team
sub undercover_skin
sub undercover_name
sub feignmsg
sub next_feign_time
sub disptimer
sub hit_in_current_animation
sub head_shot_vector
sub leg_damage
sub FlashTime
sub cheat_level
sub antispam_detpack
sub antispam_assault_cannon
sub antispam_cannon_air
sub antispam_incendiary_cannon
sub StatusString
sub StatusStringLines
sub StatusStringTime
sub StatusRefreshTime
sub StatusGrenTime
sub ScannerOn
sub allowvote
sub tf_id
sub clientkillforce
sub clientkillfree
sub is_admin
sub admin_mode
sub ip
sub vote
sub bvote
sub fo_num_login_tries
sub fo_next_login_try
sub login_required
sub fo_login
sub login
sub login_in_progress
sub classtime
sub goalrunningtime
sub caps
sub touches
sub kills
sub teamkills
sub sbteamkills
sub deaths;
sub afflicted
sub teamafflicted
sub damagegiven
sub damagetaken
sub last_throw
sub airblast_cooldown
sub last_playerclass
sub nextpc
sub is_spectator
sub oldbuttons
